- name: Golang Setup
  block:
    - name: Download and install
      install_go:
        dest: '{{ ansible_env.HOME }}/.local/lib'

    - name: Find the executables
      find:
        paths: '{{ ansible_env.HOME }}/.local/lib/go/bin'
        file_type: file
      register: exe_files

    - name: Make sure dest directory exists
      ansible.builtin.file:
        state: directory
        path: '{{ ansible_env.HOME }}/.local/bin'

    - name: Link the executables
      ansible.builtin.file:
        state: link
        src: '{{ item.path }}'
        dest: '{{ ansible_env.HOME }}/.local/bin/{{ item.path | basename }}'
      loop: '{{ exe_files.files }}'
      loop_control:
        label: '{{ item.path | basename }}'
