- block:
    - name: Enable openh264
      community.general.dnf_config_manager:
        name: fedora-cisco-openh264
        state: enabled

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Enable rpmfusion-free
      ansible.builtin.dnf:
        name:
          - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
        disable_gpg_check: yes
      when: "'rpmfusion-free-release' not in ansible_facts.packages"

    - name: Enable rpmfusion-nonfree
      ansible.builtin.dnf:
        name:
          - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
        disable_gpg_check: yes
      when: "'rpmfusion-nonfree-release' not in ansible_facts.packages"
  become: yes
