#!/bin/bash

set -euo pipefail

cd "$(dirname "$(readlink -f "$0")")"

python3 -m venv .venv
source .venv/bin/activate

if [[ ! -f ".venv/bin/ansible" ]]; then
  python3 -m pip install ansible
fi

echo 'You can customize your installation by editing local.yml'
echo 'Bootstrapping localhost...'
export ANSIBLE_LOCALHOST_WARNING=False
export ANSIBLE_INVENTORY_UNPARSED_WARNING=False
ansible-playbook local.yml --ask-become-pass
