#!/bin/bash

set -euo pipefail

cd "$(dirname "$(readlink -f "$0")")"

python3 -m venv .venv
source .venv/bin/activate

if [[ ! -f ".venv/bin/ansible" ]]; then
  python3 -m pip install ansible psutil
fi

ansible-playbook workstation.yml --ask-become-pass
