- hosts: localhost
  roles:
    - no_gnome_software
    - vscode
    - nvidia
    - ffmpeg
    - google_chrome
    # - texlive
    - workstation
  vars:
    fullname: Zhangyuan Nie
    email: yuan@znie.org
