- name: Download and install Go
  install_go:
    dest: "{{ ansible_env.HOME }}/.local/lib"

- name: Find Go's executables
  find:
    paths: "{{ ansible_env.HOME }}/.local/lib/go/bin"
    file_type: file
  register: exe_files

- name: Make sure .local/bin is a directory
  ansible.builtin.file:
    state: directory
    path: "{{ ansible_env.HOME }}/.local/bin"

- name: Link Go's executables
  ansible.builtin.file:
    state: link
    src: "{{ item.path }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/{{ item.path | basename }}"
  loop: "{{ exe_files.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
