- name: Setup the home directory
  vars:
    files_dir: '{{ role_path }}/files/home'
  block:
    - name: GnuPG directory
      file:
        path: '{{ ansible_env.HOME }}/.gnupg'
        state: directory
        mode: '700'
    - name: GnuPG config
      copy:
        src: gpg.conf
        dest: '{{ ansible_env.HOME }}/.gnupg/gpg.conf'
        mode: '700'

    - name: Create Projects directory
      file:
        state: directory
        path: '{{ ansible_env.HOME }}/Projects'

    - name: Find the files
      find:
        paths: '{{ files_dir }}'
        hidden: yes
        recurse: yes
        file_type: file
      register: home_files

    - name: Set src_paths
      set_fact:
        src_paths: "{{ home_files.files | map(attribute='path') | list }}"

    - name: Set dest_paths
      set_fact:
        dest_paths: '{{ src_paths | replace(files_dir, ansible_env.HOME) }}'

    - name: Create the directories
      file:
        path: '{{ item }}'
        state: directory
        recurse: yes
      loop: "{{ dest_paths | map('dirname') | unique | reject('eq', ansible_env.HOME) | list }}"

    - name: Link the files
      file:
        src: '{{ item[0] }}'
        dest: '{{ item[1] }}'
        state: link
        force: yes
      loop: '{{ src_paths | zip(dest_paths) | list }}'
      loop_control:
        label: '{{ item[1] }}'
