- name: Remove unwanted packages
  dnf:
    name: "{{ packages }}"
    state: absent
    autoremove: yes
  vars:
    packages:
      - PackageKit
      - gnome-software
      - fedora-chromium-config
      - gnome-clocks
      - gnome-maps
      - gnome-weather
      - gnome-calendar

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: Install packages
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      # dev
      - git
      - git-filter-repo
      - java-11-openjdk-devel
      - java-11-openjdk-src
      - nodejs
      - yarnpkg
      - python3-pip
      - gcc
      - gcc-c++
      - clang
      - valgrind
      - gtk4-devel
      - libadwaita-devel
      - make
      - meson
      - ImageMagick
      # rust
      - rust
      - rust-src
      - cargo
      - rust-analyzer
      - rustfmt
      # apps
      - evolution
      - evolution-ews
      - htop
      - inkscape
      - nautilus-python
      - neovim
      - seahorse
      - seahorse-nautilus
      - sqlitebrowser
      - vlc
      - unrar
